version: "3"
services:
  postgres:
    env_file:
      - .env
    image: postgres:11.3-alpine

  processing:
    build: processing
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ${DATA_FOLDER}:/mnt/data
      - ${PROCESSING_FOLDER}:/mnt/code

  zookeeper:
    build: 
      context: .
      dockerfile: containers/Dockerfile.kafka
    command: ["bin/zookeeper-server-start.sh", "config/zookeeper.properties"]

  kafka:
    build: 
      context: .
      dockerfile: containers/Dockerfile.kafka
    command: ["bin/kafka-server-start.sh", "config/server.properties"]
    depends_on:
      - zookeeper
