version: "3"
services:
  postgres:
    env_file:
      - .env
    image: postgres:11.3-alpine

  processing:
    build: processing
    depends_on:
      - postgres
      - kafka
    env_file:
      - .env
    volumes:
      - ${DATA_FOLDER}:/mnt/data
      - ${PROCESSING_FOLDER}:/mnt/code

  zookeeper:
    build: 
      context: .
      dockerfile: containers/Dockerfile.kafka
    command: ["bin/zookeeper-server-start.sh", "config/zookeeper.properties"]

  kafka:
    build: 
      context: .
      dockerfile: containers/Dockerfile.kafka
    command: ["bin/kafka-server-start.sh", "config/server.properties"]
    depends_on:
      - zookeeper

  consumer:
    build:
      context: ./processing/process_gazettes
      dockerfile: Dockerfile
    volumes:
      - ${DATA_FOLDER}:/mnt/data
      - ./processing/process_gazettes:/mnt/code
    depends_on:
      - kafka
      - dgraph
    env_file:
      - .env
    command: ["python3", "consumer.py"]

  dgraph:
    image: dgraph/standalone:latest
    ports:
      - 8080:8080
      - 8000:8000
      - 9080:9080
