version: "3"
services:
  postgres:
    image: postgres:11.3-alpine
    container_name: postgres
    env_file:  .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:$POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_DOCKER_PORT}
    networks:
      - production-network

  processing:
    build:
      dockerfile: Dockerfile
      context: ./processing
    image: diario-oficial_processing:lastest
    container_name: processing
    command: "scrapy crawl am_manaus"
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ${DATA_FOLDER}:/mnt/data
      - ${PROCESSING_FOLDER}:/mnt/code
    networks:
      - production-network

networks:
  production-network:
    driver: bridge
