version: "3"
services:
  processing:
    build:
      context: processing
      args:
        - LOCAL_USER_ID
    env_file:
      - .env
    volumes:
      - ${DATA_FOLDER}:/mnt/data
      - ${PROCESSING_FOLDER}:/mnt/code
