on:
  push:
    paths:
    - 'data_collection/gazette/spiders/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r data_collection/requirements.txt
      - name: Run added/modified spider
        run: |
          cd data_collection
          for spider in $(git diff --name-only main | grep -o "gazette\/spiders\/.*\.py"); do scrapy runspider ${spider}; done
